# Generated by Django 3.2.8 on 2021-10-31 09:27

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='мобильный телефон')),
                ('communication_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='ссылка на социальную сеть')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес доставки')),
                ('consent_to_processing_db', models.BooleanField(verbose_name='согласие на обработку персональных данных')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий к заказу')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес доставки')),
                ('deliver_to', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время доставки')),
                ('order_status', models.CharField(choices=[('Заявка обрабатывается', 'заявка обрабатывается'), ('Готовим ваш торт', 'готовим ваш торт'), ('Торт в пути', 'торт в пути'), ('Торт у вас', 'торт у вас')], db_index=True, default='Заявка обрабатывается', max_length=30, verbose_name='Статус заказа')),
                ('cost', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Стоимость торта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels_count', models.CharField(choices=[('1', '1 уровень'), ('2', '2 уровня'), ('3', '3 уровня')], db_index=True, max_length=50, verbose_name='количество уровней')),
                ('cake_form', models.CharField(choices=[('Квадрат', 'квадрат'), ('Круг', 'круг'), ('Прямоугольник', 'прямоугольник')], db_index=True, max_length=50, verbose_name='форма торта')),
                ('topping', multiselectfield.db.fields.MultiSelectField(choices=[('Без топпинга', 'без топпинга'), ('Белый соус', 'белый соус'), ('Карамельный сироп', 'карамельный сироп'), ('Кленовый сироп', 'кленовый сироп'), ('Клубничный сироп', 'клубничный сироп'), ('Черничный сироп', 'черничный сироп'), ('Молочный шоколад', 'молочный шоколад')], max_length=50, verbose_name='топпинг')),
                ('berries', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ежевика', 'ежевика'), ('Малина', 'малина'), ('Голубика', 'голубика'), ('Клубника', 'клубника')], db_index=True, max_length=50, null=True, verbose_name='ягоды')),
                ('decor', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Фисташки', 'фисташки'), ('Безе', 'безе'), ('Фундук', 'фундук'), ('Пекан', 'пекан'), ('Маршмеллоу', 'маршмеллоу'), ('Марципан', 'марципан')], db_index=True, max_length=50, null=True, verbose_name='декор')),
                ('inscription', models.CharField(blank=True, max_length=50, null=True, verbose_name='надпись')),
                ('promocode', models.CharField(blank=True, max_length=50, null=True, verbose_name='промокод')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='cakesite.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'торт',
                'verbose_name_plural': 'торты',
            },
        ),
    ]
